server:
  adminMinThreads: 1
  adminMaxThreads: 64
  adminContextPath: /
  applicationContextPath: /
  applicationConnectors:
    - type: http
      port: 9101
  adminConnectors:
    - type: http
      port: 9102
swagger:
  resourcePackage: com.ontotext.annotation.resource