---
swagger: "2.0"
info:
  description: "Annotation API (subset of W3C Open Annotation). Annotate content with\
    \ concepts"
  version: "v0.0.1"
  title: "Annotation API"
  termsOfService: "http://www.yourterms.com"
  contact:
    name: "Jem Rayfield"
    url: "http://ontotext.com"
    email: "jem.rayfield@ontotext.com"
host: "localhost:8089"
basePath: "/annotations"
tags:
- name: "Annotation API using a subset of the W3C open annotation Annotation protocol\
    \ https:www.w3.orgTRannotation-protocol"
schemes:
- "http"
- "https"
