---
swagger: "2.0"
info:
  description: "Annotation API (subset of W3C Open Annotation). Annotate content with\
    \ concepts"
  version: "v0.0.1"
  title: "Annotation API"
  termsOfService: "http://www.yourterms.com"
  contact:
    name: "Jem Rayfield"
    url: "http://ontotext.com"
    email: "jem.rayfield@ontotext.com"
host: "localhost:8089"
basePath: "/annotations"
tags:
- name: "Annotation API"
schemes:
- "http"
- "https"
paths:
  /annotations/{annotationId}:
    get:
      tags:
      - "Annotation API"
      summary: "Finds Annotation by id"
      description: "A single annotation can be returned"
      operationId: "annotation"
      produces:
      - "application/ld+json; profile=\"http://www.w3.org/ns/anno.jsonld\""
      parameters:
      - name: "annotationId"
        in: "path"
        description: "Annotation Id to be retrieved. Must be a valid UUID"
        required: true
        type: "string"
      responses:
        200:
          description: "Success"
          headers:
            X-Cache:
              type: "boolean"
              description: "Explains whether or not a cache was used"
        400:
          description: "Invalid Annotation Id supplied"
        404:
          description: "Annotation not found"
definitions:
Annotation:
    properties:
      annotation_id:
        type: string
        description: Unique identifier representing a specific annotation