PUT /annotations?contentId=tsk550fnfym8&asynch=false HTTP/1.1
Host: localhost:9101
Content-Type: application/json
X-Request-ID: 4b6c6796-0fca-11e7-93ae-92361f002671

{ "items": [{ "@graph": [{ "@id": "http://data.ontotext.com/annotation/tsn5dytas6bk", "type": "Annotation", "motivation": "tagging", "body": { "@id": "http:/data.ontotext.com/annotation/body/tsk9k4aunvgg", "type": "SpecificResource", "purpose": "tagging", "source": "http://ontology.ontotext.com/resource/tslsht48nsw0", "ontoa:hasFeatures": { "@id": "http:/data.ontotext.com/annotation/features/tsk9k4aunvg2", "ontoa:class": { "@id": "http://ontology.ontotext.com/taxonomy/Keyphrase" }, "ontoa:confidence": "0.89", "ontoa:relevanceScore": "0.63", "ontoa:tagType": "http://ontotext.com/annotation/about", "ontoa:type": "concept", "ontoa:status": "suggested" } }, "target": { "@id": "http://data.ontotext.com/content/tsk550fnfym8", "type": "Text", "selector": { "type": "TextPositionSelector", "start": 412, "end": 795 } } }], "@context": ["http://www.w3.org/ns/anno.jsonld", {"ontoa": "http://ontology.ontotext.com/annotation#"}], "@id": "http://data.ontotext.com/content/tsk550fnfym8" }] }